### ISSUE TITLE
bug when searching places from the search bar

### ISSUE THREAD

**Issue by momo-celeste** [FacilMap/facilmap#154] opened 2021-05-13 11:21 UTC
Hello, 
when i write on the search bar a place to locate on the map, often there is no response and a bug comes up, also making it difficult to drag the map and move around or to zoom. 
Giulia, 

thanks for the map service, i use it alot !

**Comment by cdauth** [comment] 2021-05-13 12:00
Hey,

thanks for the report. Could you give a concrete example what exactly you type into the search bar and what exact error comes up?

**Comment by momo-celeste** [comment] 2021-05-13 12:07
I am searching for 'Montenero Sabino' for example, and the warnings coming up in the console are :

warning 1: Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (838725 px). Occurrences of will-change over the budget will be ignored. SqnXbkMeUHVaSNXQ

warning 2: MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. leaflet-src.js:28:5

Can it help?

**Comment by cdauth** [comment] 2021-05-13 12:17
These warnings are very interesting, but I think they are not related to the problem.

Right now I can reproduce that searching for something doesn't give any result. I think there might be a problem with the rate limiting of the search, maybe it got stuck. I will try to change the algorithm of the rate limiting, but for now I restarted the server and the search should work again.

What I'm not sure yet is how this impacts the ability to drag the map?

**Comment by momo-celeste** [comment] 2021-05-13 12:49
I'm not knowledgeable on programming, so don't know if i can help a lot now, but i got this as well (I attached a screenshot, it migh be more readable): 

"Tried to send a 'target-destroyed-form' event on an already destroyed actor 'watcher' Actor.js:58:15
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode” browser.xhtml
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
Use of nsIFile in content process is deprecated. 5 NetUtil.jsm:253:8
[Exception... "Component returned failure code
![Screenshot from 2021-05-13 14-47-59](https://user-images.githubusercontent.com/61320716/118127619-3ce88780-b3fa-11eb-8bd8-c028623c444b.png)
: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
Use of nsIFile in content process is deprecated. 5 NetUtil.jsm:253:8
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
Empty string passed to getElementById(). browser-custom-element.js:377:22
TypeError: result.range is undefined"

**Comment by cdauth** [comment] 2021-05-22 22:48
I'm not getting any of the errors that you are seeing. It's hard to tell whether they even come from FacilMap or rather from some browser plugins that you have installed.

I'm still not sure what precise problem you are experiencing. Was the only problem that the search was loading forever without showing any results, or was there another problem?

**Comment by momo-celeste** [comment] 2021-05-23 12:04
Hello,
So i've tried to open a clean facilmap (not edited or marked, etc) with a new firefox profile, where no plug-ins should interfere. I opened it both on my computer and on someone else's. Bugs keep on  occurring, but now the dragging part seems to work better. Still though, if you drag the map after having searched for a place in the search bar, at every dragging, the map takes time reloading and placing the route or the markers back on. I've made a quick video to show you what i mean, hope it can help :) Could it have something to do with the fact that i am in Italy? 

https://user-images.githubusercontent.com/61320716/119259572-32cf4180-bbcf-11eb-9e98-254d52073b90.mp4

**Comment by cdauth** [comment] 2021-05-23 12:46
Oha, that looks very broken. Thank you, the video is very helpful. I tried the same steps as you did and could reproduce the same behaviour in Firefox. I will try to investigate and fix the problem as soon as possible.

In the meantime, if you want to use the map without these problems, you could use a different browser such as Chrome.

**Comment by cdauth** [comment] 2021-05-23 15:54
It turns out that I introduced this bug on the 7th of May as part of commit a047a55 and didn't notice that it broke things in Firefox, as I was only testing in Chrome.

This bug should be fixed now. Thanks for reporting! Please let me know if something still doesn't work.

**Closed by cdauth** 2021-05-23 15:54 UTC
