### ISSUE TITLE
changing the read-only link URL to something else displays a map without any data (even if there's any available.)

### ISSUE THREAD

**Issue by govvin** [FacilMap/facilmap#150] opened 2021-04-29 00:52 UTC
Changing the admin and edit URLs work fine for me, but when I change the read-only URL it points to an empty map.

I expected that it will point to the same map, in  a read-only mode.

**Comment by govvin** [comment] 2021-05-02 07:24
5/2, update.

I initially reported that when I changed the read-only link, it points to a new map. That's apparently incorrect.

What appears to have been happening is that it doesn't display any data. I can the custom text and links  in the legend box, but none of the data.

**Comment by cdauth** [comment] 2021-05-02 11:37
I can reproduce the problem. It seems that somehow the map objects are not updated to belong to the new URL. Since FacilMap internally uses the read-only URL for associating map objects with a map, it also means that when you change the read-only URL, the map objects are also missing on the writable/admin URLs. To get them back, you can change the read-only URL back to the original value.

I will try to investigate and fix this as soon as possible.

**Comment by cdauth** [comment] 2021-05-03 01:07
This should be fixed now. For some reason the foreign key constraints were not in the database. I wonder if this has actually every worked. Thanks for reporting!

If you lost any data because of this, please let me know.

**Closed by cdauth** 2021-05-03 01:07 UTC

**Comment by govvin** [comment] 2021-05-03 01:17
Thank you for fixing it @cdauth 

I confirm that it now works as expected, and happily, I don't see any data loss.
