### ISSUE TITLE
geojson export produces GPX file

### ISSUE THREAD

**Issue by govvin** [FacilMap/facilmap#319] opened 2024-12-05 00:42 UTC
![image](https://github.com/user-attachments/assets/932b05e0-5bab-460d-8e31-e1c441549972)

I'm trying to export a map as a geojson, and observed the following:

- it produces a GPX, even when geojson is selected as the format when the export method is "download"
- it generates a GPX, even when geojson is selected as the format when the export method is "generate link"
- it suggests a file name based on a previous map i made, not the current one I'm working on
- the generated link works and produces the geojson file

**Comment by cdauth** [comment] 2024-12-05 20:49
That's strange! Does it happen all the time or only in some cases?

**Comment by govvin** [comment] 2024-12-06 01:06
Well, I only encountered it yesterday, so I'm trying it again right now -- and now it works as expected! :star_struck: 

I tried it several times yesterday, and it was consistently giving me a GPX file instead. 

It seems to working again.

Sorry for the noise. :pray:

**Comment by cdauth** [comment] 2024-12-08 15:26
Maybe it was a random error. In the last days I had a few strange errors as well and after restarting the FacilMap server they suddenly disappeared again.

Or maybe it is somehow related to how you opened the map. I could imagine that maybe you had one map open and then switched to another one using the “Collaborative maps” menu? However, I could not reproduce the problem like that.

I’m closing the issue for now, if it happens again, feel free to open it again.

**Closed by cdauth** 2024-12-08 15:26 UTC
